Mobile View Portfolio Website
tonnymuchui/Portfolio pull request #1
Opened 2022-08-18 18:06 UTC by tonnymuchui

Created mobile view portfolio using HTML and CSS. I also used linters to check my code and CSS

2022-08-18 18:53 UTC, MahmoudBakr23 reviewed
# Hi @tonnymuchui 😃, 

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

## **Invalid Submission**

- Please fix the linters 

_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

2022-08-19 15:16 UTC, smunozmo requested changes
Hi @tonnymuchui, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

<img src="https://media1.giphy.com/media/z5cNqbFbMTDA4/giphy.gif"/>

Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 15:16 UTC, smunozmo commented on index.html
> +                <li><label id="checkbox_toggle" class="hamburger">&#9776;</label></li>
- [ ] Your portfolio is looking great! However, I would suggest making your hamburger icon clickable by using an `a` tag, also there is a bullet on the left of your icon that is not in the Figma template, it would be better to remove it. 

<img width="74" alt="Screen Shot 2022-08-19 at 10 01 25 AM" src="https://user-images.githubusercontent.com/83717285/185648283-5c2fa9f1-b9cd-4e9f-b815-92b4e44f7e52.png">

2022-08-19 15:16 UTC, smunozmo commented on index.html
> +                <h1 class="header-text">I'm Tonny Glad to see you</h1>
- [ ] Great job using the best practice for HTML semantics! Let's make it even better by reducing the vertical space between the title (h1) and the description (p) as shown in the Figma template:

|Template|Your design|
|---|---|
|<img width="368" alt="Screen Shot 2022-08-19 at 10 11 36 AM" src="https://user-images.githubusercontent.com/83717285/185650492-fc0e6988-1fae-4780-a898-58d922fd5f6b.png">|<img width="445" alt="Screen Shot 2022-08-19 at 10 11 46 AM" src="https://user-images.githubusercontent.com/83717285/185650549-5e14626c-2111-4005-8079-05ef061640fc.png">|

2022-08-19 19:24 UTC, Kamba56 approved these changes
Hi @tonnymuchui, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters passed
- [ ] Correct use of Github flow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 19:24 UTC, Kamba56 commented on index.html
> +                <h1 class="header-text">I'm Tonny Glad to see you</h1>
- [Optional] Please note that it is best practice and a convention to use indentation of 2 spaces in all your documents. You can check [here](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) for more details.

- [Optional] It's better to follow commit message standards by making them capitalized and in the imperative form (Example: 'Modify readme file' instead of 'modified readme'). This way, your commit history will be more readable and more professional ✨

2022-08-19 19:24 UTC, Kamba56 commented on css/styles.css
> +  font-style: normal;
- [Optional] Please note that it is best practice not to repeat multiple `!important` properties in your CSS. Check [here](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) for more details.

- [Optional] Consider creating a class for the font family and assigning the class to the HTML elements that requires it rather than repeatedly using the class. This is best practice for [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) code.

2022-08-19 19:35 UTC, merged

2022-08-19 19:35 UTC, tonnymuchui commented
working on Portfolio mobile view website page. Made use of HTML&CSS and linters.

2022-10-11 09:02 UTC, tonnymuchui commented
Thank you so much for the project review and feedback. I will work on the
professional coding practices you highlighted. kind regards

On Fri, Aug 19, 2022 at 10:24 PM Toma John Musa ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @tonnymuchui <https://github.com/tonnymuchui>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> Highlights
>
>    - ALl linters passed
>    - Correct use of Github flow
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/tonnymuchui/Portfolio/pull/1#discussion_r950498909>:
>
> > +<head>
>
> +    <meta charset="UTF-8">
>
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +    <title>Portfolio</title>
>
> +    <link rel="stylesheet" href="css/styles.css">
>
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
>
> +    <link rel="preconnect" href="https://fonts.googleapis.com">
>
> +    <link rel="preconnect" href="https://fonts.googleapis.com">
>
> +    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
>
> +    <link ***@***.***&display=swap" rel="stylesheet">
>
> +</head>
>
> +<body>
>
> +    <header class="navbar">
>
> +        <a href="#" class="nav-brand">My Logo</a>
>
> +        <nav>
>
> +            <ul>
>
> +                <li><label id="checkbox_toggle" class="hamburger"><a href="#">&#9776;</a></label></li>
>
> +            </ul>
>
> +        </nav>
>
> +    </header>
>
> +    <main>
>
> +        <section class="about-section">
>
> +            <div class="align-center-text">
>
> +                <h1 class="header-text">I'm Tonny Glad to see you</h1>
>
>
>
>    -
>
>    [Optional] Please note that it is best practice and a convention to
>    use indentation of 2 spaces in all your documents. You can check here
>    <https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md>
>    for more details.
>    -
>
>    [Optional] It's better to follow commit message standards by making
>    them capitalized and in the imperative form (Example: 'Modify readme file'
>    instead of 'modified readme'). This way, your commit history will be more
>    readable and more professional ✨
>
> ------------------------------
>
> In css/styles.css
> <https://github.com/tonnymuchui/Portfolio/pull/1#discussion_r950501344>:
>
> > +  font-family: 'Poppins', sans-serif !important;
>
> +  font-style: normal;
>
> +  font-weight: 700;
>
> +  font-size: 40px;
>
> +  display: flex;
>
> +  align-items: center;
>
> +  color: #172b4d;
>
> +  flex: none;
>
> +  order: 0;
>
> +  flex-grow: 0;
>
> +}
>
> +
>
> +.content-text {
>
> +  width: 300px;
>
> +  height: 100px;
>
> +  font-family: 'Poppins', sans-serif !important;
>
> +  font-style: normal;
>
>
>
>    -
>
>    [Optional] Please note that it is best practice not to repeat multiple
>    !important properties in your CSS. Check here
>    <https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md>
>    for more details.
>    -
>
>    [Optional] Consider creating a class for the font family and assigning
>    the class to the HTML elements that requires it rather than repeatedly
>    using the class. This is best practice for DRY
>    <https://en.wikipedia.org/wiki/Don%27t_repeat_yourself> code.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tonnymuchui/Portfolio/pull/1#pullrequestreview-1079269416>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJVSLTNG5G6DPFYGPPAA46TVZ7NOHANCNFSM566BSTOQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>