Works popup window
tonnymuchui/Portfolio pull request #12
Opened 2022-09-08 06:48 UTC by tonnymuchui

Added JavaScript array to store all of the information for all projects. Implemented Js interaction, When the user clicks (or taps) the button to check project details, the popup with details about the project appears.

2022-09-08 08:17 UTC, ShoiraTa reviewed
Hi team,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Modal window works as expected ✔️ 
- You passed all the Linters! ✔️ 
- Data is retrieved dynamically ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

- [ ] Please check the readme file, some sections look broken: 

<img width="945" alt="Screenshot 2022-09-08 at 11 17 41" src="https://user-images.githubusercontent.com/77038610/189072005-61a344c8-c7bb-443e-9b38-c038bab7d626.png">


_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-08 08:17 UTC, ShoiraTa commented on index.html
> +          <div class="container"></div>
- [ ] After the recent changes, I can see that the structure of project cards has been broken, please make sure that your layoput is same as provided on Figma:

Your design  | Figma design
------------- | -------------
<img width="543" alt="Screenshot 2022-09-08 at 11 11 59" src="https://user-images.githubusercontent.com/77038610/189070756-68f6605a-c1b4-44ce-9425-3773b2192960.png"> | <img width="288" alt="Screenshot 2022-09-08 at 11 10 16" src="https://user-images.githubusercontent.com/77038610/189070347-814914e5-9f9b-4644-b607-d4309570c2b1.png">

As you can see, project's text content should be on the left or on the right depending on the flow. But in your case, it is always on the right

2022-09-08 08:17 UTC, ShoiraTa commented on js/script.js
> +  <h3 class="work-heading ${index}">${card.title}</h3>
- [ ] Please add a little more space below the project title and date info:

Your design  | Figma design
------------- | -------------
<img width="736" alt="Screenshot 2022-09-08 at 11 15 43" src="https://user-images.githubusercontent.com/77038610/189071607-c1af88f1-4053-4fd5-8d37-a892031628cd.png">  | <img width="596" alt="Screenshot 2022-09-08 at 11 15 26" src="https://user-images.githubusercontent.com/77038610/189071539-83771dc8-b326-41bd-bafb-1d6bc1d1827d.png">

2022-09-08 14:16 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @tonnymuchui, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - Correct use of GitHub flow. ✔️
 - Good modal design. ✔️ 

## Aspects to improve ♻️

- [ ] As the previous code reviewer mentioned, your README file looks broken. Please try to manipulate the images and the sections so it looks more professional. If you try to make the changes through Github, you can click on the 'Preview' button to see how it looks. Be aware of the attributes that you are applying to the images.
-Your README:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/61919617/189145768-3eb7187e-8722-46e6-9c3f-b1fe4f56c355.png">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-08 16:40 UTC, addod19 approved these changes
### Hi team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Nice job fixing the README file 💯 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-08 16:44 UTC, merged

2022-10-11 08:48 UTC, tonnymuchui commented
I was requesting if it could be possible we spend like 10min on zoom you
help me to know how I will implement project card on the right

On Thu, Sep 8, 2022 at 11:18 AM Shoira ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Hi team,
>
> 👍 This is good to make it this far, your project is really nice,
> congratulations on the good work you have done so far.
>
> *First let me to point out:*
>
>    - Modal window works as expected ✔️
>    - You passed all the Linters! ✔️
>    - Data is retrieved dynamically ✔️
>
> Keep on coding, good job so far! 👏
>
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
>
> <https://camo.githubusercontent.com/7a3175b24229512cc970aece8b2e2de8a06ce098a4f0ba2c4079f9a4f9152c29/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f644550476b6e5269456e6965632f67697068792e676966>
> Required Changes ♻️
>
>    - Please check the readme file, some sections look broken:
>
> [image: Screenshot 2022-09-08 at 11 17 41]
> <https://user-images.githubusercontent.com/77038610/189072005-61a344c8-c7bb-443e-9b38-c038bab7d626.png>
>
> *Check the comments under the review.*
> ------------------------------
>
> Cheers and Happy coding! 👏 👏 👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear by mentioning my Github username.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/tonnymuchui/Portfolio/pull/12#discussion_r965642734>:
>
> > -                  onclick="window.location.href = 'https://github.com/tonnymuchui/Portfolio';"
>
> -                >
>
> -                  See Project
>
> -                </button>
>
> -              </div>
>
> -            </div>
>
> -          </div>
>
> -          <div class="work-card">
>
> -            <img
>
> -              class="img img-last"
>
> -              src="images/image2desktop.png"
>
> -              alt="image2desktop-img"
>
> -            />
>
> -            <div class="align-center-text">
>
> -              <h3 class="work-heading">Multi-Post Stories</h3>
>
> -              <ul class="dev-date">
>
> -                <li class="canopy">CANOPY</li>
>
> -                <li class="bullet">&#9679;&nbsp;&nbsp;&nbsp;Back End Dev</li>
>
> -                <li class="bullet">&#9679;&nbsp;&nbsp;&nbsp;2015</li>
>
> -              </ul>
>
> -              <p class="works-content-p">
>
> -                Experimental content creation feature that allows users to add
>
> -                to an existing story over the course of a day without spamming
>
> -                their friends.
>
> -              </p>
>
> -              <ul class="badges">
>
> -                <li class="works-badge">html</li>
>
> -                <li class="works-badge">css</li>
>
> -                <li class="works-badge">javaScript</li>
>
> -              </ul>
>
> -              <button
>
> -                class="btn"
>
> -                onclick="window.location.href = 'https://github.com/tonnymuchui/Portfolio';"
>
> -              >
>
> -                See Project
>
> -              </button>
>
> -            </div>
>
> -          </div>
>
> -          <div class="work-card">
>
> -            <img
>
> -              class="img"
>
> -              src="images/image3desktop.png"
>
> -              alt="image3desktop-img"
>
> -            />
>
> -            <div class="align-center-text">
>
> -              <h3 class="work-heading">Facebook 360</h3>
>
> -              <ul class="dev-date">
>
> -                <li class="canopy">CANOPY</li>
>
> -                <li class="bullet">&#9679;&nbsp;&nbsp;&nbsp;Back End Dev</li>
>
> -                <li class="bullet">&#9679;&nbsp;&nbsp;&nbsp;2015</li>
>
> -              </ul>
>
> -              <p class="works-content-p">
>
> -                Exploring the future of media in Facebook's first Virtual
>
> -                Reality app; a place to discover and enjoy 360 photos and videos
>
> -                on Gear VR.
>
> -              </p>
>
> -              <ul class="badges">
>
> -                <li class="works-badge">html</li>
>
> -                <li class="works-badge">css</li>
>
> -                <li class="works-badge">javaScript</li>
>
> -              </ul>
>
> -              <button
>
> -                class="btn"
>
> -                onclick="window.location.href = 'https://github.com/tonnymuchui/Portfolio';"
>
> -              >
>
> -                See Project
>
> -              </button>
>
> -            </div>
>
> -          </div>
>
> -          <div class="work-card">
>
> -            <img
>
> -              class="img img-last"
>
> -              src="images/image4desktop.png"
>
> -              alt="image4desktop-img"
>
> -            />
>
> -            <div class="align-center-text">
>
> -              <h3 class="work-heading">Uber Navigation</h3>
>
> -              <ul class="dev-date">
>
> -                <li class="canopy">CANOPY</li>
>
> -                <li class="bullet">&#9679;&nbsp;&nbsp;&nbsp;Back End Dev</li>
>
> -                <li class="bullet">&#9679;&nbsp;&nbsp;&nbsp;2015</li>
>
> -              </ul>
>
> -              <p class="works-content-p">
>
> -                A smart assistant to make driving more safe, efficient, and fun
>
> -                by unlocking your most expensive computer: your car.
>
> -              </p>
>
> -              <ul class="badges">
>
> -                <li class="works-badge">html</li>
>
> -                <li class="works-badge">css</li>
>
> -                <li class="works-badge">javaScript</li>
>
> -              </ul>
>
> -              <button
>
> -                class="btn"
>
> -                onclick="window.location.href = 'https://github.com/tonnymuchui/Portfolio';"
>
> -              >
>
> -                See Project
>
> -              </button>
>
> -            </div>
>
> -          </div>
>
> +          <div class="container"></div>
>
>
>
>    - After the recent changes, I can see that the structure of project
>    cards has been broken, please make sure that your layoput is same as
>    provided on Figma:
>
> Your design Figma design
> [image: Screenshot 2022-09-08 at 11 11 59]
> <https://user-images.githubusercontent.com/77038610/189070756-68f6605a-c1b4-44ce-9425-3773b2192960.png> [image:
> Screenshot 2022-09-08 at 11 10 16]
> <https://user-images.githubusercontent.com/77038610/189070347-814914e5-9f9b-4644-b607-d4309570c2b1.png>
>
> As you can see, project's text content should be on the left or on the
> right depending on the flow. But in your case, it is always on the right
> ------------------------------
>
> In js/script.js
> <https://github.com/tonnymuchui/Portfolio/pull/12#discussion_r965647042>:
>
> > +      'A daily selection of privately personalized reads; no accounts or sign-ups required.',
>
> +    languages: ['html', 'css', 'javascript'],
>
> +  },
>
> +];
>
> +
>
> +const worksCard = cards.map(
>
> +  (card, index) => `
>
> +<section class="works ${index}">
>
> +<div class="work-card">
>
> +<img
>
> +  class="img"
>
> +  src="${card.imageM}"
>
> +  alt="SnapshootPortfolio02-img"
>
> +/>
>
> +<div class="align-center-text">
>
> +  <h3 class="work-heading ${index}">${card.title}</h3>
>
>
>
>    - Please add a little more space below the project title and date info:
>
> Your design Figma design
> [image: Screenshot 2022-09-08 at 11 15 43]
> <https [...]