My contact
tonnymuchui/Portfolio pull request #5
Opened 2022-08-24 14:55 UTC by tonnymuchui

2022-08-24 15:36 UTC, tonnymuchui commented
worked on the footer section html&css. where I added contact information

2022-08-24 16:23 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @tonnymuchui 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 16:23 UTC, tresorsawasawa commented on index.html
> +      </footer>
- [ ] Kindly make sure you also add the missing **Horizontal** line at the bottom of the page to stick to the Figma design.

| Figma Design | Your Design |
| -------------------- | ---------------------- |
| ![Screenshot from 2022-08-24 18-19-39](https://user-images.githubusercontent.com/83042742/186470709-2a5288a0-7c84-46ff-af1f-4a69f4910542.png) | ![Screenshot from 2022-08-24 18-19-07](https://user-images.githubusercontent.com/83042742/186470848-1058fe7e-0104-4109-8d23-033d9c671a29.png) |

2022-08-24 16:29 UTC, tonnymuchui commented
Working on them right now. Thank you.

On Wed, 24 Aug 2022, 19:23 Tresor Sawasawa ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> STATUS: REQUIRED CHANGES ♻️♻️
>
> Hi @tonnymuchui <https://github.com/tonnymuchui>
> Good job so far! I know you worked hard to implement this project, I
> really appreciate the effort you put in! But there are some issues that you
> still need to work on to go to the next project but you are almost there!
>
> [image: almost-there]
> <https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif>
> To highlight 🍾
>
>    - All linters are passing ✔️
>    - Good commit history ✔️
>    - Good PR description ✔️
>    - Follow GitHub flow ✔️
>
> Required changes ♻️ ♻️
>
>    - Check the comments under the review.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
>
> *Feel free to leave any questions or comments in the PR thread if
> something is not 100% clear. Please ping me @tresorsawasawa
> <https://github.com/tresorsawasawa> when you comment so I can receive the
> notification or use slack with the same name.*
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/tonnymuchui/Portfolio/pull/5#discussion_r953992952>:
>
> > +            <ul>
>
> +              <li>
>
> +                <label for="name"></label>
>
> +                <input
>
> +                  class="name"
>
> +                  name="name"
>
> +                  type="text"
>
> +                  placeholder="Enter your Name"
>
> +                  id="name"
>
> +                  maxlength="30"
>
> +                  required="required"
>
> +                />
>
> +              </li>
>
> +              <li>
>
> +                <label for="mail"></label>
>
> +                <input
>
> +                  class="email"
>
> +                  name="email"
>
> +                  type="email"
>
> +                  placeholder="Enter your Email"
>
> +                  id="mail"
>
> +                  required="required"
>
> +                />
>
> +              </li>
>
> +              <li>
>
> +                <label for="msg"></label>
>
> +                <textarea
>
> +                  class="message"
>
> +                  id="msg"
>
> +                  name="text"
>
> +                  placeholder="Write your text in here"
>
> +                  rows="8"
>
> +                  cols="30"
>
> +                  maxlength="500"
>
> +                  required="required"
>
> +                ></textarea>
>
> +              </li>
>
> +              <li>
>
> +                <button class="getin getin1" type="submit">Get It Touch</button>
>
> +              </li>
>
>
>
>    - Kindly make sure all the inputs elements and the Get In Touch button
>    follow the design like your chosen Figma template(e.g.: alignment of inputs,
>    buttons, and textarea; padding(top, bottom, left & right) used in
>    inputs & textarea fields, the width of inputs & textarea fields, used
>    font-family and padding in the textarea filed, alignment of the Get In
>    Touch button,...). Make sure you check all the details from the Figma
>    template and apply them to your project
>
> Figma design Your Design
> [image: Screenshot from 2022-08-24 18-00-43]
> <https://user-images.githubusercontent.com/83042742/186466681-3bc4b096-3b47-454c-a2b8-9c2050c31500.png> [image:
> Screenshot from 2022-08-24 17-49-30]
> <https://user-images.githubusercontent.com/83042742/186466775-b6f145f5-35cc-4fe5-9efc-60da8d163ea6.png>
> ------------------------------
>
> In index.html
> <https://github.com/tonnymuchui/Portfolio/pull/5#discussion_r954012004>:
>
> > +            </ul>
>
> +          </form>
>
> +        </div>
>
> +      </footer>
>
>
>
>    - Kindly make sure you also add the missing *Horizontal* line at the
>    bottom of the page to stick to the Figma design.
>
> Figma Design Your Design
> [image: Screenshot from 2022-08-24 18-19-39]
> <https://user-images.githubusercontent.com/83042742/186470709-2a5288a0-7c84-46ff-af1f-4a69f4910542.png> [image:
> Screenshot from 2022-08-24 18-19-07]
> <https://user-images.githubusercontent.com/83042742/186470848-1058fe7e-0104-4109-8d23-033d9c671a29.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tonnymuchui/Portfolio/pull/5#pullrequestreview-1084086529>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJVSLTIU3IZU4LULMY7667LV2ZEBLANCNFSM57PVKEEA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-27 13:33 UTC, tonnymuchui commented
added a horizontal line to the footer & fixed submit button

2022-08-27 13:46 UTC, awais-amjed approved these changes
# STATUS: APPROVED 🥳

Hi @tonnymuchui , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations on implementing the requested changes! 🎉👏🥇✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] No linter issues ✔️

![gif](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

## Optional suggestions

- [ ] It would be nice if you can fix the spacing around your website and between different elements to match the Figma design 🤗

Your design:
![image](https://user-images.githubusercontent.com/73714615/187033021-1d9b530c-027b-4da9-a92e-66ce50118f1f.png)

Figma design:
![image](https://user-images.githubusercontent.com/73714615/187033029-e5def16a-a0df-4e93-8231-924381692a6e.png)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 15:41 UTC, merged